// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xndorttfogfjwfpfqvfh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhuZG9ydHRmb2dmandmcGZxdmZoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMwMTAzNDYsImV4cCI6MjA1ODU4NjM0Nn0.fXXW5Mp50c4P3Sw5QajLaNuJY1_NbNtcZEgABTEIe5E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);